/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainDashboardImport } from './routes/main-dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as MainDashboardNhoodImport } from './routes/main-dashboard.$nhood'

// Create/Update Routes

const MainDashboardRoute = MainDashboardImport.update({
  id: '/main-dashboard',
  path: '/main-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainDashboardNhoodRoute = MainDashboardNhoodImport.update({
  id: '/$nhood',
  path: '/$nhood',
  getParentRoute: () => MainDashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/main-dashboard': {
      id: '/main-dashboard'
      path: '/main-dashboard'
      fullPath: '/main-dashboard'
      preLoaderRoute: typeof MainDashboardImport
      parentRoute: typeof rootRoute
    }
    '/main-dashboard/$nhood': {
      id: '/main-dashboard/$nhood'
      path: '/$nhood'
      fullPath: '/main-dashboard/$nhood'
      preLoaderRoute: typeof MainDashboardNhoodImport
      parentRoute: typeof MainDashboardImport
    }
  }
}

// Create and export the route tree

interface MainDashboardRouteChildren {
  MainDashboardNhoodRoute: typeof MainDashboardNhoodRoute
}

const MainDashboardRouteChildren: MainDashboardRouteChildren = {
  MainDashboardNhoodRoute: MainDashboardNhoodRoute,
}

const MainDashboardRouteWithChildren = MainDashboardRoute._addFileChildren(
  MainDashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-dashboard': typeof MainDashboardRouteWithChildren
  '/main-dashboard/$nhood': typeof MainDashboardNhoodRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-dashboard': typeof MainDashboardRouteWithChildren
  '/main-dashboard/$nhood': typeof MainDashboardNhoodRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/main-dashboard': typeof MainDashboardRouteWithChildren
  '/main-dashboard/$nhood': typeof MainDashboardNhoodRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/main-dashboard' | '/main-dashboard/$nhood'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main-dashboard' | '/main-dashboard/$nhood'
  id: '__root__' | '/' | '/main-dashboard' | '/main-dashboard/$nhood'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainDashboardRoute: typeof MainDashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainDashboardRoute: MainDashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main-dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/main-dashboard": {
      "filePath": "main-dashboard.tsx",
      "children": [
        "/main-dashboard/$nhood"
      ]
    },
    "/main-dashboard/$nhood": {
      "filePath": "main-dashboard.$nhood.tsx",
      "parent": "/main-dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
